// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
        _ "embed"
        "fyne.io/fyne/v2"
)

//go:embed Creepster-Regular.ttf
var resourceCreepsterRegularTtfData []byte
var resourceCreepsterRegularTtf = &fyne.StaticResource{
        StaticName:    "Creepster-Regular.ttf",
        StaticContent: resourceCreepsterRegularTtfData,
}
   